### ISSUE TITLE
Is this even a problem

### ISSUE THREAD

**Issue by AimLow-SMM** [JosieBigler/movie-bros#17]
The useEffect containing fetchData still has two instances so when the page loads fetchData gets called twice
`setRatings([...data.data]);` ratings is being hard set so there's technically no problem

**Comment by JosieBigler** [comment]
The two instances you see is first the declaration of `fetchData` and then it's invocation. 

We have to do this because the API calls are async but `useEffect` is not. So we declare an async function within `useEffect` and then call it and handle the returned promise. 

[I followed this guide](https://devtrium.com/posts/async-functions-useeffect). 

If you slap a console.log in `fetchData` it only fires once.
